create database customer_behaviour;
use customer_behaviour;

-- 1. what is the total revenue generated by male vs female customers

select gender, sum(purchase_amount) as revenue from customer group by gender;

rename table clean_customer_behaviour to customer;

select * from customer;

-- 2. which customers used a discount but still spent more than the average purchase amount.

select customer_id , purchase_amount from customer where discount_applied = "Yes" and 
purchase_amount >= (select avg(purchase_amount) from customer);

-- 3. which are the top 5 products with the highest average review ratings.

select item_purchased, avg(review_rating) as 'Avg Product Rating' from customer 
group by item_purchased order by avg(review_rating) desc limit 5;

-- 4. compare the average purchase amounts between standard and express shipping.

select shipping_type, avg(purchase_amount) as 'avg purchase amount' from customer
where shipping_type in ('Standard','Express') group by shipping_type;

-- 5.  do subscribed customers spend more ? compare avg spend an total revenue between subscribers and non-subscriber.

SELECT 
    subscription_status,
    COUNT(customer_id) AS total_customer,
    ROUND(AVG(purchase_amount), 2) AS avg_spend,
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM
    customer
GROUP BY subscription_status
ORDER BY total_revenue , avg_spend DESC;

-- 6. which 5 product have the highest percentage of purchase with discount applied.

select item_purchased, ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/ count(*) ,2) as discount_rate
from customer group by item_purchased order by discount_rate desc limit 5;

-- 7. segment customers into new, retuning, and loyal based on their total number of previous purchase ,
-- show the count of each segment.

with customer_type as (select customer_id, previous_purchases,
case when previous_purchases = 1 then 'New'
when previous_purchases between 2 and 10 then 'Returning'
else 'Loyal' 
end as customer_segment from customer)
select customer_segment, count(*) as "Number of Customers"
from customer_type group by customer_segment;

-- 8. what are the top 3 most purchased products within each category.

with item_counts as (select item_purchased, category, count(customer_id) as total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id) desc) as item_rank
from customer 
group by category, item_purchased)
select item_rank, category, item_purchased, total_orders from item_counts
where item_rank <=3;

-- 9. are customers who are repeat buyers(more than 5 previous purchases) also likely to subscribe.

select subscription_status,
count(customer_id) as repeat_buyers from customer where previous_purchases > 5
group by subscription_status;

-- 10. what is the revenue contribution of each age group.

select age_group , sum(purchase_amount) as total_revenue from customer group by age_group
order by total_revenue desc ;

